services:
  - name: postgres:9.6
    alias: postgres

variables:
  # https://docs.gitlab.com/runner/configuration/feature-flags.html
  FF_TIMESTAMPS: 1
  # PostgreSQL
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo
  POSTGRES_DB: odoo
  VERSION: "14.0"

job:
  tags:
    - _odoo
  cache:
    paths:
      - /root/.cache/pip
  timeout: 2h
  image: docker-registry.decgroupe.com/erp/oca/oca-ci/py3.8-ocb14.0-dec:latest
  script:
    # Add nano command
    - apt install -y nano
    # Add killall command
    - apt install -y psmisc 
    # Install dependencies (old way using oca_dependencies.txt)
    - oca_clone_dependencies
    # Force install of older lxml 
    - pip install lxml==4.6.5
    # Install aerolib to venv
    - git clone https://github.com/decgroupe/aeroolib.git /tmp/aeroolib
    - pip install -e /tmp/aeroolib
    # - cd /opt/odoo
    # Install addons and dependencies (new way using setuptool)
    - oca_install_addons
    # Check licenses
    # - manifestoo -d . check-licenses
    # Check development status
    # - manifestoo -d . check-dev-status --default-dev-status=Beta
    # Initialize test db
    - oca_init_test_database
    # Exclude some modules
    - EXCLUDE=product_create_prefill,website_sale_product_public_code,mail_activity_team_schedule,mail_activity_schedule_dhxgantt,project_schedule,mrp_schedule,sale_timesheet_project_schedule,web_report_workflow,account_report_qweb,sale_report_qweb
    # - INCLUDE=procurement_exception
    # Run tests with coverage
    - oca_run_tests
    # - sleep 8h || true
  artifacts:
    paths:
      - /tmp/odoo
    expire_in: 3 day
    when: always
