# Copyright (C) DEC SARL, Inc - All Rights Reserved.
# Written by Yann Papouin <ypa at decgroupe.com>, Aug 2020

import logging

from odoo import _, api, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class ProcurementGroup(models.Model):
    _inherit = "procurement.group"

    @api.model
    def _run_scheduler_tasks(self, use_new_cursor=False, company_id=False):
        # check confirmed moves in MO or pickings
        self.sudo()._try_mts_moves_without_orderpoint(company_id=company_id)
        result = super()._run_scheduler_tasks(
            use_new_cursor=use_new_cursor, company_id=company_id
        )
        # basic copy/paste of odoo's original code
        if "scheduler_task_done" in self._context:
            task_done = (
                self._context.get("scheduler_task_done", {"task_done": 0})["task_done"]
                + 1
            )
            self._context["scheduler_task_done"]["task_done"] = task_done
        else:
            task_done = self._get_scheduler_tasks_to_do()
        if use_new_cursor:
            self.env["ir.cron"]._notify_progress(
                done=task_done, remaining=self._get_scheduler_tasks_to_do() - task_done
            )
            self.env.cr.commit()  # pylint: disable=E8102
        return result

    @api.model
    def _get_scheduler_tasks_to_do(self):
        return super()._get_scheduler_tasks_to_do() + 1

    @api.model
    def _try_mts_moves_without_orderpoint(self, company_id=False):
        if company_id and self.env.user.company_id.id != company_id:
            # To ensure that the company_id is taken into account for
            # all the processes triggered by this method
            # i.e. If a PO is generated by the run of the procurements the
            # sequence to use is the one for the specified company not the
            # one of the user's company
            self = self.with_context(company_id=company_id, force_company=company_id)
        # Find and select only valid moves
        moves_to_reorder = self._get_mts_moves_to_reorder()
        for product_id in moves_to_reorder.mapped("product_id"):
            try:
                with self._cr.savepoint():
                    self._action_cannot_reorder_product(product_id)
            # only catch UserError
            except UserError as error:
                _logger.exception(
                    "Error while reodering product %s: %s",
                    product_id.display_name,
                    error,
                )

    @api.model
    def _get_mts_moves_to_reorder(self):
        # Search all active pickings
        picking_ids = self.env["stock.picking"].search(
            [("state", "in", ("waiting", "confirmed", "assigned"))]
        )
        # Select only valid moves
        picking_res = self._filter_mts_picking_moves_to_reorder(picking_ids)

        # Search all active manufacturing orders
        production_ids = self.env["mrp.production"].search(
            [("state", "not in", ("done", "cancel"))]
        )
        # Select only valid moves
        production_res = self._filter_mts_production_moves_to_reorder(production_ids)
        return picking_res + production_res

    @api.model
    def _filter_mts_picking_moves_to_reorder(self, picking_ids):
        stock_location_id = self.env["stock.move"].get_stock_location()
        return picking_ids.mapped("move_ids").filtered(
            lambda x: x.state in ("confirmed")
            and x.procure_method == "make_to_stock"
            and x.product_id.nbr_reordering_rules == 0
            and x.location_id == stock_location_id
            and not x.created_purchase_line_ids
            and not x.move_orig_ids.purchase_line_id
            and not x.created_production_id
            and not x.orderpoint_created_production_ids
            and not x.orderpoint_created_purchase_line_ids
        )

    @api.model
    def _filter_mts_production_moves_to_reorder(self, production_ids):
        stock_location_id = self.env["stock.move"].get_stock_location()
        return production_ids.mapped("move_raw_ids").filtered(
            lambda x: x.state in ("confirmed")
            and x.procure_method == "make_to_stock"
            and x.product_id.nbr_reordering_rules == 0
            and x.location_id == stock_location_id
            and not x.created_purchase_line_ids
            and not x.move_orig_ids.purchase_line_id
            and not x.created_production_id
            and not x.orderpoint_created_production_ids
            and not x.orderpoint_created_purchase_line_ids
        )

    @api.model
    def _action_cannot_reorder_product(self, product_id):
        product_id.ensure_one()
        error_msg = _("Not enough stock and no minimum orderpoint rule")
        raise UserError(error_msg)
