# -*- coding: utf-8 -*-
# Copyright (C) DEC SARL, Inc - All Rights Reserved.
# Written by Yann Papouin <ypa at decgroupe.com>, Oct 2021

from odoo import _, api, fields, models


class SoftwareLicense(models.Model):
    _inherit = 'software.license'

    pass_id = fields.Many2one(
        comodel_name='software.license.pass',
        string='Pass',
    )
    pack_line_ids = fields.One2many(
        comodel_name='software.license.pack.line',
        inverse_name='license_id',
        string="Pack Lines",
        copy=False,
        help="Licenses dynamically generated by this pass to match pack "
        "content"
    )

    def _name_get(self):
        res = super()._name_get()
        if self.pack_line_ids:
            names = [
                x.pack_id.display_name for x in self.pack_line_ids
            ]
            names = ', '.join(names)
            res = _('%s (%s for %s)') % (res, self.serial, names)
        return res
