#!/usr/bin/env bash
# build draftly bundle for Odoo static assets
# usage: ./build_draftly.sh [--skip-install]
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
OUT_DIR="$SCRIPT_DIR/static/src/lib"
OUT_FILE="$OUT_DIR/draftly.bundle.js"

mkdir -p "$BUILD_DIR" "$OUT_DIR"

# -- install deps unless skipped -----------------------------------------------
if [[ "$1" != "--skip-install" ]]; then
    echo "[1/3] installing npm dependencies..."
    cd "$BUILD_DIR"
    # create a package.json if not present so npm installs locally here
    if [[ ! -f package.json ]]; then
        npm init -y --scope="" > /dev/null
    fi
    npm install --save-exact \
        draftly \
        @codemirror/commands \
        @codemirror/lang-markdown \
        @codemirror/language \
        @codemirror/language-data \
        @codemirror/state \
        @codemirror/view \
        esbuild
    cd "$SCRIPT_DIR"
else
    echo "[1/3] skipping npm install (--skip-install)"
fi

# -- write entry point ---------------------------------------------------------
echo "[2/3] writing entry point..."
cat > "$BUILD_DIR/entry.js" <<'EOF'
// this file is AUTO-GENERATED by build_draftly.sh - do not edit manually.
// entry point: re-export everything the Odoo widget needs
export { EditorState } from "@codemirror/state";
export { EditorView, keymap, lineNumbers, highlightActiveLine } from "@codemirror/view";
export { defaultKeymap, historyKeymap, history } from "@codemirror/commands";
export { markdown } from "@codemirror/lang-markdown";
export { languages } from "@codemirror/language-data";
export {
    draftly,
    allPlugins,
    ThemeEnum,
    DraftlyPlugin,
    preview,
    generateCSS,
} from "draftly";
// pre-built extension array for code mode (avoids IIFE export issues with syntaxHighlighting)
import { syntaxHighlighting, defaultHighlightStyle } from "@codemirror/language";
import { lineNumbers as cmLineNumbers, highlightActiveLine } from "@codemirror/view";
export const codeExtensions = [
    cmLineNumbers(),
    highlightActiveLine(),
    syntaxHighlighting(defaultHighlightStyle),
];
EOF

# -- bundle with esbuild -------------------------------------------------------
echo "[3/3] bundling with esbuild..."
cd "$BUILD_DIR"
node_modules/.bin/esbuild entry.js \
    --bundle \
    --format=iife \
    --global-name=Draftly \
    --platform=browser \
    --loader:.woff2=dataurl \
    --loader:.woff=dataurl \
    --loader:.ttf=dataurl \
    --minify \
    --outfile="$OUT_FILE"

echo ""
echo "done: $OUT_FILE ($(du -sh "$OUT_FILE" | cut -f1))"
