{
    "name": "Procurement Traceability",
    "version": "14.0.1.0.0",
    "author": "DEC",
    "website": "https://www.decgroupe.com",
    "depends": [
        "sale",
        "sale_action_view",
        "purchase",
        "purchase_action_view",
        "stock",
        "stock_action_view",
        "sale_stock",
        "purchase_stock",
        "purchase_line_procurement_group",
        "mrp",
        "mrp_action_view",
    ],
    "data": [
        "views/procurement.xml",
        "views/mrp_production.xml",
        "views/stock_move.xml",
        "views/stock_picking.xml",
        "views/sale_order.xml",
        "views/purchase_order.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
