{
    "name": "Product Reference",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "author": "DEC",
    "website": "https://decgroupe.com",
    "depends": [
        "auth_api_key",
        "base",
        "base_xmlid",
        "web_onchange_values",
        "uom",
        "product",
        "mrp",
        "product_category_analytic",
        "product_reference_management",
        "product_state_review",
        "product_location",
        "product_prices",
        "product_legacy_routes",
        "product_tagging",
        "product_pack_order_type",
        "product_pack_line",
        "product_picking",
        "product_public_code",
        "mrp_production_request",
        "mrp_bom_dates",
        "mrp_bom_supplier",
        "mrp_bom_prices",
        "mrp_buy_consu",
        "sale_purchase",
        "sale_timesheet",
        "stock_available_unreserved",
    ],
    "data": [
        "security/model_security.xml",
        "security/ir.model.access.csv",
        "views/product_template.xml",
        "views/ref_attribute.xml",
        "views/ref_property.xml",
        "views/ref_reference.xml",
        "views/ref_reference_line.xml",
        "views/ref_category.xml",
        "views/ref_category_line.xml",
        "views/ref_version.xml",
        "views/res_config_settings.xml",
        "wizard/change_product_state_by_category.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/ref_categories.xml",
        "demo/ref_references.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "product_reference/static/src/scss/style.scss",
        ]
    },
    "installable": True,
}
