{
    "name": "Software License (pass)",
    "version": "14.0.1.0.0",
    "author": "DEC",
    "website": "https://www.decgroupe.com",
    "depends": [
        "software_license_token",
        "software_license_feature",
        "software_license_keygen",
        "auth_signup_delegate",
        "sequence_reset_period",
        "base_sequence_first_number",
        "mail_qweb",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/assets.xml",
        "views/software_license_pass.xml",
        "views/software_license.xml",
        "views/software_license_pack.xml",
        "views/software_license_pack_line.xml",
        "views/menu.xml",
        "data/sequence.xml",
        "data/ir_ui_view.xml",
        "data/mail_template.xml",
        "data/uom.xml",
    ],
    "demo": [
        "demo/software_license_pack.xml",
        "demo/software_license_pass.xml",
    ],
    "installable": True,
}
